name: Build macOS Binary

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Preinstalled Python
        run: |
          arch -x86_64 /usr/bin/python3 --version

      - name: Set up Virtual Environment
        run: |
          arch -x86_64 /usr/bin/python3 -m venv venv
          source venv/bin/activate
          pip install --no-cache-dir -r requirements.txt

      - name: Reinstall numpy cleanly
        run: |
          source venv/bin/activate
          pip uninstall -y numpy
          pip install numpy

      - name: Debug installed dependencies
        run: |
          source venv/bin/activate
          pip freeze

      - name: Regenerate wrapper.spec
        run: |
          source venv/bin/activate
          arch -x86_64 pyinstaller --name=converter --onefile --specpath . wrapper.py

      - name: Build binary using PyInstaller
        run: |
          source venv/bin/activate
          mkdir -p release

          # Debugging the environment
          echo "Contents of venv/bin:"
          ls -l venv/bin

          # Run PyInstaller with the regenerated wrapper.spec
          arch -x86_64 pyinstaller wrapper.spec

          # Debug the dist directory
          echo "Contents of dist directory:"
          ls -l dist

          # Package the binary into a tar.gz file
          tar -czvf release/mumma_converter-macOS.tar.gz -C dist mumma_converter    

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mumma_converter-macOS
          path: release/mumma_converter-macOS.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mumma_converter-macOS

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: ${{ github.ref_name }}
          file: mumma_converter-macOS.tar.gz
