name: Build macOS Binary

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: macos-14  # Use a specific macOS version supported by GitHub Actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Locate Homebrew
        run: |
          if [[ "$(uname -m)" == "arm64" ]]; then
            echo "Homebrew is on an Apple Silicon Mac"
            eval "$(/opt/homebrew/bin/brew shellenv)"
          else
            echo "Homebrew is on an Intel Mac"
            eval "$(/usr/local/bin/brew shellenv)"
          fi

      - name: Install Python via Homebrew (x86_64)
        run: |
          arch -x86_64 $(which brew) install python@3.9

      - name: Install dependencies (x86_64)
        run: |
          arch -x86_64 /usr/local/bin/python3.9 -m pip install --no-cache-dir -r requirements.txt

      - name: Set up Virtual Environment
        run: |
          arch -x86_64 /usr/local/bin/python3.9 -m venv venv
          source venv/bin/activate
          pip install --no-cache-dir -r requirements.txt

      - name: Build binary using wrapper.spec
        run: |
          mkdir -p release

          # Debugging the environment
          echo "Contents of venv/bin:"
          ls -l venv/bin

          # Run PyInstaller with wrapper.spec
          arch -x86_64 pyinstaller wrapper.spec

          # Package the binary into a tar.gz file
          tar -czvf release/mumma_converter-macOS.tar.gz -C dist mumma_converter    

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mumma_converter-macOS
          path: release/mumma_converter-macOS.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mumma_converter-macOS

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: ${{ github.ref_name }}
          file: mumma_converter-macOS.tar.gz
