name: Build and Release macOS Binary

on:
  push:
    tags:
      - 'v*' # Trigger workflow only on version tags (e.g., v1.0, v2.3)
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-macos:
    name: Build macOS Binary
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Binary with PyInstaller
      run: |
        pyinstaller --onefile --name csv_to_qif main.py

    - name: Archive Binary
      run: |
        mkdir -p release
        mv dist/csv_to_qif release/
        tar -czvf release/csv_to_qif-macOS.tar.gz -C release csv_to_qif

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: csv_to_qif-macOS
        path: release/csv_to_qif-macOS.tar.gz

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: release/csv_to_qif-macOS.tar.gz
