name: Build macOS Binary

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Preinstalled Python
        run: |
          arch -x86_64 /usr/bin/python3 --version

      - name: Recreate Virtual Environment (x86_64)
        run: |
          rm -rf venv  # Clean any existing virtual environment
          arch -x86_64 /usr/bin/python3 -m venv venv
          source venv/bin/activate
          arch -x86_64 pip install --no-cache-dir --force-reinstall -r requirements.txt

      - name: Install PyInstaller
        run: |
          source venv/bin/activate
          arch -x86_64 pip install pyinstaller

      - name: Debug Installed Dependencies
        run: |
          source venv/bin/activate
          pip freeze

      - name: Regenerate wrapper.spec
        run: |
          source venv/bin/activate
          arch -x86_64 pyinstaller --name=converter --onefile --specpath . wrapper.py

      - name: Build Binary Using PyInstaller
        run: |
          source venv/bin/activate
          mkdir -p release
          arch -x86_64 pyinstaller wrapper.spec

      - name: Debug dist Directory
        run: |
          echo "Contents of dist directory:"
          ls -l dist

      - name: Package the Binary
        run: |
          tar -czvf release/mumma_converter-macOS.tar.gz -C dist mumma_converter

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mumma_converter-macOS
          path: release/mumma_converter-macOS.tar.gz


  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mumma_converter-macOS

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: ${{ github.ref_name }}
          file: mumma_converter-macOS.tar.gz
